articles:
  - url: "http://www.aktuality.sk/clanok/384171/roky-sleduje-kotlebovcov-v-banskej-bystrici-ozili-mafianske-praktiky/"
    name: "V Banskej Bystrici ožili „mafiánske“ praktiky"
  - url: "http://www.aktuality.sk/clanok/271100/kotlebovo-ako-vladne-zupan-marian-kotlebu-v-banskej-bystrici/"
    name: "Ako vládne župan Marian Kotleba v Banskej Bystrici"
  - url: "https://www.facebook.com/kotlebafasista/posts/306281329741734"
    name: "Facebook: 28.10.2016"
  - url: "http://hnonline.sk/slovensko/850690-kotleba-mal-v-parlamente-rasisticke-narazky-zvlastne-tvare-a-neslovansky-vzhlad"
    name: "Žitňanská odsúdila Kotlebove rasistické narážky"
  - url: "http://www.aktuality.sk/clanok/389224/nazor-stanislava-miceva-fasizmus-a-jeho-klony-su-spat/"
    name: "Fašizmus a jeho klony sú späť"
  - url: "https://www.facebook.com/photo.php?fbid=10154653830983361&set=a.10151026450113361.450366.588498360&type=3&theater"
    name: "Facebook: 15.11.2016"
