articles:
  - url: "http://www.aktuality.sk/clanok/384171/roky-sleduje-kotlebovcov-v-banskej-bystrici-ozili-mafianske-praktiky/"
    name: "V Banskej Bystrici ožili „mafiánske“ praktiky"
  - url: "http://www.aktuality.sk/clanok/271100/kotlebovo-ako-vladne-zupan-marian-kotlebu-v-banskej-bystrici/"
    name: "Ako vládne župan Marian Kotleba v Banskej Bystrici"
  - url: "https://www.facebook.com/kotlebafasista/posts/306281329741734"
    name: "Facebook: 28.10.2016"
  - url: "http://hnonline.sk/slovensko/850690-kotleba-mal-v-parlamente-rasisticke-narazky-zvlastne-tvare-a-neslovansky-vzhlad"
    name: "Žitňanská odsúdila Kotlebove rasistické narážky"
  - url: "http://www.aktuality.sk/clanok/389224/nazor-stanislava-miceva-fasizmus-a-jeho-klony-su-spat/"
    name: "Fašizmus a jeho klony sú späť"
  - url: "https://www.facebook.com/photo.php?fbid=10154653830983361&set=a.10151026450113361.450366.588498360&type=3&theater"
    name: "Facebook: 15.11.2016"
  - url: "http://domov.sme.sk/c/20362322/kotleba-vymenil-byt-za-rodinny-dom-kupil-ho-za-stranicke-peniaze.html"
    name: "Kotleba vymenil byt za rodinný dom, kúpil ho za stranícke peniaze"
  - url: "https://scontent-ams3-1.xx.fbcdn.net/v/t31.0-8/16251786_10154540051478401_3281600481638773410_o.jpg?oh=0b273f58423167632cbd07e700bd880d&oe=5903CB65"
    name: "Status Stanislava Mizíka"
  - url: "https://www.facebook.com/zuzana.hanzelova.1/posts/10209967262990861"
    name: "Hovorí to internet. Čiže to nie je moje vyjadrenie."
  - url: "https://www.facebook.com/projektn.sk/posts/1378209118935310?comment_id=1378260828930139"
    name: "Facebook: 26.1.2017"
  - url: "https://scontent-ams3-1.xx.fbcdn.net/v/t1.0-9/16174597_355426344827232_6792256450468191715_n.jpg?oh=191831806d3e003ba1f0243953b0c4e3&oe=591D4381"
    name: "Mimovladky"
  - url: "https://www.aktuality.sk/clanok/301284/po-roku-a-pol-hodnotia-kotlebu-kraj-pripravil-o-miliony-pomohol-rodine/"
    name: "Po roku a pol hodnotia Kotlebu: pomohol rodine, kraj pripravil o milióny"
  - url: "http://www.ta3.com/clanok/1052910/posielaju-nominanti-kotlebovi-20-percent-mzdy-zupan-priznal-ucet.html"
    name: "Posielajú nominanti Kotlebovi 20 percent mzdy? Župan priznal účet"
  - url: "http://hnonline.sk/slovensko/850690-zitnanska-odsudila-kotlebove-rasisticke-narazky-je-to-hysteria-spajana-so-zidovstvom"
    name: "Žitňanská odsúdila Kotlebove rasistické narážky"
  - url: "https://aktualne.atlas.sk/odmena-za-vernost-kotlebovi-prisluhovaci-rozhoduju-o-nemalych-sumach/slovensko/politika/"
    name: "Odmena za vernosť? Kotlebovi prisluhovači rozhodujú o nemalých sumách"
  - url: "http://www.etrend.sk/ekonomika/kotlebov-kraj-ilegalne-zamestnaval-ochrankara-z-eurofondov-mozno-nedostanu-nic.html"
    name: "Kotlebov kraj ilegálne zamestnával ochrankára"
  - url: "https://mladiprotifasizmu.sk/5-dovodov-preco-su-podla-jakuba-drabika-kotlebovci-fasisti/"
    name: "5 dôvodov"
  - url: "https://www.youtube.com/watch?v=y-ypsG4Ir3s"
    name: "Fašisti sa domáhali vstupu na školu, kde hrali predstavenie o Natálke"
  - url: "http://hnonline.sk/slovensko/914919-kotleba-zamestnaval-nacierno-bystricky-kraj-kvoli-nemu-prisiel-o-miliony-na-opravy-ciest"
    name: "Kotleba zamestnával načierno."
  - url: "https://transparency.blog.sme.sk/c/454200/pri-vlade-kotlebu-treba-byt-naozaj-na-strazi.html"
    name: "Pri vláde Kotlebu treba byť naozaj na stráži"
